# any logged-in user authenticated through the
# console needs READONLY access to these resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-extensions-reader
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  - consolenotifications
  - consoleexternalloglinks
  - consoleclidownloads
  - consoleyamlsamples
  - consoleplugins
  verbs:
  - get
  - list
  - watch
